# Generated by Django 5.2.13 on 2026-04-09 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Cliente', models.CharField(max_length=150)),
                ('Unidade', models.CharField(max_length=100, unique=True)),
                ('Codigo_unidade', models.CharField(max_length=100, unique=True)),
                ('UF', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('ID_registro', models.AutoField(primary_key=True, serialize=False)),
                ('km_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsavel', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='VMO.cliente')),
            ],
        ),
    ]
